### ISSUE TITLE
.out file not usable with flash programmer 2

### ISSUE THREAD

**Issue by ntilau** [Venemo/cc2640-ble-broadcaster#1]
I have correctly built the project and debugged it with CCSv6. I have a sensortag board with XDS110v3 debugger. How can I flash permanently the program? It seems like it works only with GEL

Hoping it is an easy question for you,
Best regards,
Laurent

**Comment by Venemo** [comment]
@ntilau The flash programmer can use `hex` files, right? In that case, you can add a post-build step to the CCS project that will produce a `hex` file for you.

In CCS right-click the project, hit properties. Then go to _Build_ and _Steps_, and add this as a post-build step:

```
${CG_TOOL_HEX} -order MS --memwidth=8 --romwidth=8 --intel -o      ${ProjName}.hex ${ProjName}.out
```
