### ISSUE TITLE
Hi. CC2650 problem!

### ISSUE THREAD

**Issue by WallGeorg** [Venemo/cc2640-ble-broadcaster#2]
Hi.
I want to make the bluetooth remote control with CC2650rc.
I am going to develop the firmware with IAR.
But I am beginner.
So I don't know the developing method.
I want to know your SDK install method .
I hope your help.
Best regards.

**Comment by Venemo** [comment]
@WallGeorg Hi! This is a very simple broadcaster app. For anything more serious, I suggest to use TI's BLE stack for the CC2640. I have some sample code: https://github.com/Venemo/cc26xx-ble-stack-example ― but the  best resource is TI's documentation.
